{"name": "test_InvalidUser_ErrorMessageShown", "status": "passed", "description": "Login with invalid credentials and check that username error message is shown", "attachments": [{"name": "log", "source": "1003669b-bc54-404c-b875-44ce228c64c9-attachment.txt", "type": "text/plain"}], "start": 1745225767619, "stop": 1745225768402, "uuid": "d6c5a3e3-38eb-493d-ab56-c54b29eea0c5", "historyId": "a5e4a4d72e174d211f0da7cc743eda45", "testCaseId": "a5e4a4d72e174d211f0da7cc743eda45", "fullName": "tests.test_login.TestLogin#test_InvalidUser_ErrorMessageShown", "labels": [{"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "User-PC"}, {"name": "thread", "value": "9948-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}