{"uuid": "b4a4cb3b-fc35-4848-95b9-6d2a2562bb2e", "children": ["2627bb05-4678-45cf-a709-43dfa9fec959"], "befores": [{"name": "_xunit_setup_method_fixture_TestLogin", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=135.0.7049.96)\nStacktrace:\n\tGetHandleVerifier [0x00007FF74F455355+78597]\n\tGetHandleVerifier [0x00007FF74F4553B0+78688]\n\t(No symbol) [0x00007FF74F2091AA]\n\t(No symbol) [0x00007FF74F205BA0]\n\t(No symbol) [0x00007FF74F1F6849]\n\t(No symbol) [0x00007FF74F1F85A8]\n\t(No symbol) [0x00007FF74F1F6B56]\n\t(No symbol) [0x00007FF74F1F65D6]\n\t(No symbol) [0x00007FF74F1F629A]\n\t(No symbol) [0x00007FF74F1F3F4A]\n\t(No symbol) [0x00007FF74F1F471C]\n\t(No symbol) [0x00007FF74F20D07A]\n\t(No symbol) [0x00007FF74F2B002E]\n\t(No symbol) [0x00007FF74F2870EA]\n\t(No symbol) [0x00007FF74F2AF2BB]\n\t(No symbol) [0x00007FF74F286EC3]\n\t(No symbol) [0x00007FF74F2503F8]\n\t(No symbol) [0x00007FF74F251163]\n\tGetHandleVerifier [0x00007FF74F6FEF0D+2870973]\n\tGetHandleVerifier [0x00007FF74F6F96B8+2848360]\n\tGetHandleVerifier [0x00007FF74F716993+2967875]\n\tGetHandleVerifier [0x00007FF74F47019A+188746]\n\tGetHandleVerifier [0x00007FF74F47847F+222255]\n\tGetHandleVerifier [0x00007FF74F45D2D4+111236]\n\tGetHandleVerifier [0x00007FF74F45D482+111666]\n\tGetHandleVerifier [0x00007FF74F4435A9+5465]\n\tBaseThreadInitThunk [0x00007FFAD7757374+20]\n\tRtlUserThreadStart [0x00007FFAD89BCC91+33]\n\n", "trace": "  File \"C:\\Users\\User\\anaconda3\\Lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\anaconda3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\anaconda3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\anaconda3\\Lib\\site-packages\\_pytest\\python.py\", line 899, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"C:\\Users\\User\\anaconda3\\Lib\\site-packages\\_pytest\\python.py\", line 779, in _call_with_optional_argument\n    func()\n  File \"C:\\Users\\User\\Documents\\kirpichenko_tatyana\\Lesson10\\login-web\\tests\\test_login.py\", line 23, in setup_method\n    self.driver.get(self.page_url)\n  File \"C:\\Users\\User\\anaconda3\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 454, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\User\\anaconda3\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\User\\anaconda3\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1745064238272, "stop": 1745064243883}], "start": 1745064238272, "stop": 1745064243968}