{"name": "test_additionPositiveNumbers_SuccessfulLoginAndValidResult", "status": "failed", "statusDetails": {"message": "AssertionError: assert '8' == ''\n  + 8", "trace": "self = <test_calc.TestCalculate object at 0x0000022C18540500>\n\n    def test_additionPositiveNumbers_SuccessfulLoginAndValidResult(self):\n        logging.info('trying to log in as valid user')\n        self.login_page.log_in('admin','123')\n        logging.info('trying to add up for positive numbers')\n     #   self.calculator_page.calc_add('5','3')\n        self.calculator_page.set_firstOperand('5')\n        self.calculator_page.set_secondOperand('3')\n        logging.info('123456')\n        logging.info('checking the receipt of the calculation result')\n        self.calculator_page.click_calc_button()\n        logging.info('5')\n        result_number = self.calculator_page.get_result()\n        logging.info('6')\n        print(result_number)\n>       assert '8' == result_number\nE       AssertionError: assert '8' == ''\nE         + 8\n\ntest_calc.py:54: AssertionError"}, "attachments": [{"name": "log", "source": "c51b2df2-b189-41f3-86fa-72f5f49e9703-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "49081902-b329-4428-92b9-a90d6ce5de94-attachment.txt", "type": "text/plain"}], "start": 1745353754289, "stop": 1745353755085, "uuid": "7c613ac7-eb08-4fe2-b845-8e0c7c4e763c", "historyId": "017c2c166afb58f0ef9ef9f053aa6151", "testCaseId": "017c2c166afb58f0ef9ef9f053aa6151", "fullName": "tests.test_calc.TestCalculate#test_additionPositiveNumbers_SuccessfulLoginAndValidResult", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestCalculate"}, {"name": "host", "value": "User-PC"}, {"name": "thread", "value": "15632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_calc"}]}