{"name": "test_additionPositiveNumbers_SuccessfulLoginAndValidResult", "status": "broken", "statusDetails": {"message": "NameError: name 'logging' is not defined. Did you forget to import 'logging'", "trace": "self = <test_calc.TestCalculate object at 0x000002E7A752EE40>\n\n    def test_additionPositiveNumbers_SuccessfulLoginAndValidResult(self):\n        logging.info('trying to log in as valid user')\n        self.login_page.log_in('admin','123')\n        logging.info('trying to add up for positive numbers')\n>       self.calculator_page.calc_add('5','3')\n\ntest_calc.py:44: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\calculator_page.py:16: in calc_add\n    self.click_calc_button()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.calculator_page.CalculatorPage object at 0x000002E7AA3621B0>\n\n    def click_calc_button(self):\n>       logging.info(f'clicking \"Calc\" button')\nE       NameError: name 'logging' is not defined. Did you forget to import 'logging'\n\npages\\calculator_page.py:34: NameError"}, "attachments": [{"name": "log", "source": "f0110f22-efee-4cbb-bd9f-fc0d5422be41-attachment.txt", "type": "text/plain"}], "start": 1745348758558, "stop": 1745348758968, "uuid": "0729e581-beb3-4e80-aea8-4e838dd53ebc", "historyId": "017c2c166afb58f0ef9ef9f053aa6151", "testCaseId": "017c2c166afb58f0ef9ef9f053aa6151", "fullName": "tests.test_calc.TestCalculate#test_additionPositiveNumbers_SuccessfulLoginAndValidResult", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestCalculate"}, {"name": "host", "value": "User-PC"}, {"name": "thread", "value": "4396-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_calc"}]}