{"name": "test_additionPositiveNumbers_SuccessfulLoginAndValidResult", "status": "failed", "statusDetails": {"message": "AssertionError: assert '8' == None", "trace": "self = <test_calc.TestCalculate object at 0x000002205ACC57F0>\n\n    def test_additionPositiveNumbers_SuccessfulLoginAndValidResult(self):\n        logging.info('1')\n        self.login_page.log_in('admin','123')\n        logging.info('2')\n    \n        self.calculator_page.calc_add('5','3')\n        logging.info('3')\n    \n        result = self.calculator_page.calc_result()\n        logging.info('4')\n>       assert '8' == result\nE       AssertionError: assert '8' == None\n\ntest_calc.py:50: AssertionError"}, "attachments": [{"name": "log", "source": "d28ef8f7-d64a-4146-89ed-efb64915a3d8-attachment.txt", "type": "text/plain"}], "start": 1745344379932, "stop": 1745344380453, "uuid": "abd4b628-e24b-4cdb-b5bd-b72d6a8bdbd4", "historyId": "017c2c166afb58f0ef9ef9f053aa6151", "testCaseId": "017c2c166afb58f0ef9ef9f053aa6151", "fullName": "tests.test_calc.TestCalculate#test_additionPositiveNumbers_SuccessfulLoginAndValidResult", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestCalculate"}, {"name": "host", "value": "User-PC"}, {"name": "thread", "value": "18272-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_calc"}]}