{"name": "test_additionPositiveNumbers_SuccessfulLoginAndValidResult", "status": "broken", "statusDetails": {"message": "NameError: name 'logging' is not defined. Did you forget to import 'logging'", "trace": "self = <test_calc.TestCalculate object at 0x000002DC410ED010>\n\n    def test_additionPositiveNumbers_SuccessfulLoginAndValidResult(self):\n        logging.info('trying to log in as valid user')\n        self.login_page.log_in('admin','123')\n        logging.info('trying to add up for positive numbers')\n     #   self.calculator_page.calc_add('5','3')\n        self.calculator_page.set_firstOperand('5')\n        self.calculator_page.set_secondOperand('3')\n        logging.info('123456')\n        logging.info('checking the receipt of the calculation result')\n>       self.calculator_page.click_calc_button()\n\ntest_calc.py:49: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.calculator_page.CalculatorPage object at 0x000002DC41B92120>\n\n    def click_calc_button(self):\n>       logging.info(f'clicking \"Calc\" button')\nE       NameError: name 'logging' is not defined. Did you forget to import 'logging'\n\npages\\calculator_page.py:34: NameError"}, "attachments": [{"name": "log", "source": "e9e8989b-ea91-4e0d-8b71-127861fc71a8-attachment.txt", "type": "text/plain"}], "start": 1745351779316, "stop": 1745351779744, "uuid": "706c27ae-0a85-4ce6-b941-b32266968dbc", "historyId": "017c2c166afb58f0ef9ef9f053aa6151", "testCaseId": "017c2c166afb58f0ef9ef9f053aa6151", "fullName": "tests.test_calc.TestCalculate#test_additionPositiveNumbers_SuccessfulLoginAndValidResult", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestCalculate"}, {"name": "host", "value": "User-PC"}, {"name": "thread", "value": "14460-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_calc"}]}