{"uuid": "e5d17558-c815-4e0e-b027-f13a552f2caf", "children": ["32b4f752-b9bf-4cdb-bc79-dd7bdb6fac31"], "befores": [{"name": "_xunit_setup_method_fixture_TestCalculate", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=135.0.7049.96)\nStacktrace:\n\tGetHandleVerifier [0x00007FF61ABA5305+78597]\n\tGetHandleVerifier [0x00007FF61ABA5360+78688]\n\t(No symbol) [0x00007FF61A9591AA]\n\t(No symbol) [0x00007FF61A955BA0]\n\t(No symbol) [0x00007FF61A946849]\n\t(No symbol) [0x00007FF61A9485A8]\n\t(No symbol) [0x00007FF61A946B56]\n\t(No symbol) [0x00007FF61A9465D6]\n\t(No symbol) [0x00007FF61A94629A]\n\t(No symbol) [0x00007FF61A943F4A]\n\t(No symbol) [0x00007FF61A94471C]\n\t(No symbol) [0x00007FF61A95D07A]\n\t(No symbol) [0x00007FF61AA0002E]\n\t(No symbol) [0x00007FF61A9D70EA]\n\t(No symbol) [0x00007FF61A9FF2BB]\n\t(No symbol) [0x00007FF61A9D6EC3]\n\t(No symbol) [0x00007FF61A9A03F8]\n\t(No symbol) [0x00007FF61A9A1163]\n\tGetHandleVerifier [0x00007FF61AE4EEBD+2870973]\n\tGetHandleVerifier [0x00007FF61AE49668+2848360]\n\tGetHandleVerifier [0x00007FF61AE66943+2967875]\n\tGetHandleVerifier [0x00007FF61ABC014A+188746]\n\tGetHandleVerifier [0x00007FF61ABC842F+222255]\n\tGetHandleVerifier [0x00007FF61ABAD284+111236]\n\tGetHandleVerifier [0x00007FF61ABAD432+111666]\n\tGetHandleVerifier [0x00007FF61AB93559+5465]\n\tBaseThreadInitThunk [0x00007FF8BF3B7374+20]\n\tRtlUserThreadStart [0x00007FF8C11DCC91+33]\n\n", "trace": "  File \"C:\\Users\\User\\anaconda3\\Lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\anaconda3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\anaconda3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\anaconda3\\Lib\\site-packages\\_pytest\\python.py\", line 899, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"C:\\Users\\User\\anaconda3\\Lib\\site-packages\\_pytest\\python.py\", line 779, in _call_with_optional_argument\n    func()\n  File \"C:\\Users\\User\\Documents\\kirpichenko_tatyana\\Lesson10\\calc-web\\tests\\test_calc.py\", line 22, in setup_method\n    self.driver.get(self.page_url)\n  File \"C:\\Users\\User\\anaconda3\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 454, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\User\\anaconda3\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\User\\anaconda3\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1745392482912, "stop": 1745392491701}], "start": 1745392482912, "stop": 1745392491941}