{"name": "test_additionPositiveNumbers_SuccessfulLoginAndValidResult", "status": "broken", "statusDetails": {"message": "NameError: name 'logging' is not defined. Did you forget to import 'logging'", "trace": "self = <test_calc.TestCalculate object at 0x000001BC7E3001D0>\n\n    def test_additionPositiveNumbers_SuccessfulLoginAndValidResult(self):\n        logging.info('trying to log in as valid user')\n        self.login_page.log_in('admin','123')\n        logging.info('trying to add up for positive numbers')\n>       self.calculator_page.calc_add('5','3')\n\ntest_calc.py:44: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\calculator_page.py:16: in calc_add\n    self.click_calc_button()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.calculator_page.CalculatorPage object at 0x000001BC7E301F70>\n\n    def click_calc_button(self):\n>       logging.info(f'clicking \"Calc\" button')\nE       NameError: name 'logging' is not defined. Did you forget to import 'logging'\n\npages\\calculator_page.py:34: NameError"}, "attachments": [{"name": "log", "source": "83c36781-cf0f-4889-8304-192501f1bd9d-attachment.txt", "type": "text/plain"}], "start": 1745348704191, "stop": 1745348704602, "uuid": "faa9eaa0-0260-45e8-85b3-939e3855b734", "historyId": "017c2c166afb58f0ef9ef9f053aa6151", "testCaseId": "017c2c166afb58f0ef9ef9f053aa6151", "fullName": "tests.test_calc.TestCalculate#test_additionPositiveNumbers_SuccessfulLoginAndValidResult", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestCalculate"}, {"name": "host", "value": "User-PC"}, {"name": "thread", "value": "2356-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_calc"}]}