{"name": "test_InvalidUser_ErrorMessageShown", "status": "passed", "description": "Login with invalid credentials and check that username error message is shown", "attachments": [{"name": "log", "source": "7d54101d-c1db-4f55-8cb1-86ba95fadf21-attachment.txt", "type": "text/plain"}], "start": 1745222910835, "stop": 1745222911458, "uuid": "34734f7f-603c-43f3-a480-0b5810dadc62", "historyId": "a5e4a4d72e174d211f0da7cc743eda45", "testCaseId": "a5e4a4d72e174d211f0da7cc743eda45", "fullName": "tests.test_login.TestLogin#test_InvalidUser_ErrorMessageShown", "labels": [{"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "User-PC"}, {"name": "thread", "value": "9904-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}